---
- name: This playbook install packages
  hosts: worker
  become: true
  tasks:
  - name: Install package
    yum:
      name: httpd
      state: installed
    notify: start httpd

  handlers:
  - name: start httpd
    service:
      name: httpd
      state: started
