---
- name: This playbook install packages
  hosts: worker
#   become: true
  tasks:
  - name: Install package
    yum:
      name: "{{ item }}"
      state: installed
    with_items:
      - git
      - make
      - gcc
      - wget
      - telnet
      - gzip
    
