---
- name: setup tomcat
  hosts: all
  become: yes
  tasks:
  - name: install java centos
    yum:
      name: java
      state: installed
    when: ansible_os_family == "CentOS"

  - name: install java on ubuntu
    apt: 
      name: default-jdk
      state: present
    when: ansible_os_family == "Debian"

  - name: download tomcat packages
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.70/bin/apache-tomcat-8.5.70.tar.gz
      dest: /opt

  - name: untar apache packages
    unarchive:
      src: /opt/apache-tomcat-8.5.70.tar.gz
      dest: /opt
      remote_src: yes
  
  - name: add execution permission on startup.sh
    file:
      path: /opt/apache-tomcat-8.5.70/bin/startup.sh
      mode: 0777

  - name: start tomcat services
    shell: nohup sh startup.sh
    args: 
      chdir: /opt/apache-tomcat-8.5.70/bin