---
- name: This playbook install packages
  hosts: all
  become: true
  tasks:
  - name: stop httpd service
    service:
      name: httpd
      state: stopped
    when: ansible_facts['distribution'] == "RedHat"
  - name: uninnstall httpd
    yum:
      name: httpd
      state: removed
    when: ansible_facts['distribution'] == "RedHat"

  - name: stop apache2 service
    service: 
      name: apache2
      state: stopped
    when: ansible_facts['distribution'] == "Debian"
  - name: uninstall apache2
    apt:
      name: apache2 service
      state: absent
    when: ansible_facts['distribution'] == "Debian"
