---
- name: Disabling Firewall Daemon
  service:
    name: firewalld
    state: stopped
  register: firewalld_status

- name: Firewall Daemon status
  debug:
    msg: "{{ firewalld_status }}"

- name: Disable Selinux
  selinux: 
    state: disabled

- name: Disable Swap
  shell: swapoff -a

- name: Commenting Swap entries in /etc/fstab
  replace: 
    path: /etc/fstab
    regexp: '(^/.*swap*)'
    replace: '# \1'

- name: Reloading Systemd Driver 
  systemd: 
    daemon_reload: yes
  register: SD_status


# Changing the Docker Cgroup to systemd from cgroupfs which is supported by Kubernetes!
# https://harshitdawar.medium.com/launching-a-multi-node-kubernetes-cluster-using-ansible-4a63a542e8af
# https://www.linkedin.com/pulse/ansible-role-configure-k8s-multi-node-cluster-over-aws-anudeep-nalla
 
- name: Changing the Cgroup driver of docker to 'systemd'
  copy: 
    src: ./files/daemon.json
    dest: /etc/docker/daemon.json

- name: "Restarting Docker"
  service: 
    name: docker
    state: restarted
    enabled: yes
  register: DSR_Status

- name: Letting iptables see bridged traffic
  copy:
    src: ./files/k8s.conf
    dest: /etc/sysctl.d/k8s.conf

- name: Loading br_netfilter module
  copy:
    src: ./files/br.conf
    dest: /etc/modules-load.d/k8s.conf

- name: "Refreshing sysctl"
  shell: "sysctl --system"
  register: Sysctl_Status

- name: Sysctl status
  debug: 
    msg: "{{ Sysctl_Status }}"


   



