---
# handlers file for setup-apache
- name: start httpd
  service:
    name: httpd
    state: started
    # tags: start_httpd
  ignore_errors: yes

- name: start apache2
  service:
    name: apache2
    state: started
    # tags: start_apache

- name: restart httpd 
  service:
    name: httpd
    state: restarted

- name: restart apache2 
  service:
    name: apache2
    state: restarted