---
# Configuring Yum for Epel Packages
- name: Configure the Yum with epel
  yum_repository:
    name: epel
    file: epel
    description: Configure the epel repo
    baseurl: https://dl.fedoraproject.org/pub/epel/{{ centos_ver }}/x86_64/
    gpgcheck: no
  register: epel_status

# Printing the status of the configuration on the console.
- name: Epel Status
  debug:
    msg: "Did EPEL Configuration Failed => {{  epel_status.failed }}"


- name: Configuring Docker Yum Repository
  when: epel_status.failed == false
  yum_repository:
    name: docker-ce
    file: docker-ce
    description: Configure the Docker Community Edition repo
    baseurl: https://download.docker.com/linux/centos/{{ centos_ver }}/x86_64/stable/
    gpgcheck: no
  register: docker_ce_status

- name: Docker-CE Status
  debug:
    msg: "Did Docker Configuration Failed => {{  docker_ce_status.failed }}"

# Configuring Yum for the kubernetes Repository
# - name: Configuring kubernetes Yum Repository
#   yum_repository:
#     [kubernetes]
#     name: Kubernetes
#     baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
#     enabled=1
#     gpgcheck=1
#     gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
#     exclude=kubelet kubeadm kubectl
#   register: kubernetes_status

# - name: Kubernetes Repo Status
#   debug:
#     msg: "Did Kubernetes Repo Configuration Failed => {{  kubernetes_status.failed }}"

- name: Add kubernetes repository
  ansible.builtin.template:
    src: 'kubernetes.repo.j2'
    dest: /etc/yum.repos.d/kubernetes.repo

- name: Disable Selinux
  selinux: 
    state: disabled

- name: Install kubernetes packages
  yum:
    name: [kubelet,kubeadm,kubectl]
    disable_excludes: kubernetes

- name: Enable kubelet service
  ansible.builtin.service:
    name: kubelet
    enabled: yes

- name: Update Yum Packages
  yum: update_cache=yes

# Install System Packages
- name: Install Packages needed
  package:
    name: "{{ item }}"
    state: latest
  with_items:
      - yum-utils
      - nfs-utils
      - device-mapper-persistent-data
      - ca-certificates
      - curl
      - lvm2

# # Install yum-utils (Which provides yum-config-manager utility)
# - name: Yum Config Manager.
#   shell: yum install -y 

- name: Install Docker
  yum: 
    name: docker-ce
    state: present

- name: Starting and Enabling Docker Service
  service:
    name: docker
    state: started
    enabled: yes

# - name: Install kubelet
#   yum:
#     name: kubelet-{{ kubelet_ver }}
#     state: present
#     disable_excludes: kubernetes

# - name: Install kubectl
#   yum:
#     name: kubectl-{{ kubectl_ver }}
#     state: present

# - name: Install kubeadm 
#   yum:
#     name: kubeadm-{{ kubeadm_ver }}
#     state: present

- name: Start kubelet
  service:
    name: kubelet
    state: started
    enabled: yes

- name: just force systemd to reread configs (2.4 and above)
  systemd: daemon_reload=yes



  
  




  