---
# Changing the name of the Host machine to Master
- name: Changing the name of the Host machine to Master
  shell: hostnamectl set-hostname {{ hostname_master }}

- name: Pulling images required for setting up a Kubernetes cluster
  shell: kubeadm config images pull

- name: Resetting kubeadm
  shell: kubeadm reset -f
  register: kubeadm_reset_output

- name: Resetting Kubeadm status
  debug:
    msg: "{{ kubeadm_reset_output }}"

- name: Initializing Kubernetes Cluster
  shell: 
    cmd: kubeadm init --control-plane-endpoint "{{ ad_addr }}" --upload-certs
  register: K8s_Initialize_output
  ignore_errors: yes

- name: Kubernetes Cluster Initializing status
  debug:
    msg: "{{ K8s_Initialize_output }}"
    
# Creating the required directory after Kubeadm init successful
- name: Creating the required directories
  file:
    path: "mkdir -p $HOME/.kube"
    state: directory
  register: KubeAdm_Output

- name: KubeAdm Commands Status
  debug:
    msg: "{{ KubeAdm_Output }}"

- name: Storing Logs and Generated token for future purpose.
  local_action: copy content={{ KubeAdm_Output.stdout }} dest={{ k8s_token_file }}
  become: False

# Copying the required stuff after Kubeadm init successful
- name: Copy k8s configuration file
  shell: 
    cmd: cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  register: KubeAdm_CP_Commands_Status

- name: Copying Command Status
  debug:
    msg: "{{ KubeAdm_CP_Commands_Status }}"

- name: Copying required files
  shell: |
    mkdir -p $HOME/.kube
    sudo cp -f /etc/kubernetes/admin.conf $HOME/.kube/config
    sudo chown $(id -u):$(id -g) $HOME/.kube/config

# Changing the ownership of the directories
- name: Changing ownership of directories
  shell:
    cmd: chown $(id -u):$(id -g) $HOME/.kube/config
  register: KubeAdm_Chaning_Ownership_Commands_status

- name: Changing Ownership of directories Status
  debug:
    msg: "{{ KubeAdm_Chaning_Ownership_Commands_status }}"

- name: Adding Weave Network
  shell:
    cmd: kubectl apply -f https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')
  register: Weavenet_status

- name: Adding Weave Network Status
  debug:
    msg: "{{ Weavenet_status }}"

- name: "Control plane node isolation"
  shell: kubectl taint nodes --all node-role.kubernetes.io/master-
