---
- name: Disable Swap
  shell: swapoff -a

- name: Commenting Swap entries in /etc/fstab
  replace: 
    path: /etc/fstab
    regexp: '(^/.*swap*)'
    replace: '# \1'
    
- name: Install apt-transport-https
  when: ansible_os_family == "Debian"
  apt: 
    name: apt-transport-https
    state: present
    update_cache: yes
  

- name: Add Docker APT GPG key
  when: ansible_os_family == "Debian"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  

- name: Add Docker APT repository
  when: ansible_os_family == "Debian"
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu xenial stable
    state: present
    filename: "docker"
    
- name: Add Docker yum repository on Centos{{ centos_os_ver }} 
  when: ansible_os_family == "RedHat"
  yum_repository:
    name: Docker
    description: Docker Repository
    file: docker
    baseurl: https://download.docker.com/linux/centos/{{ centos_os_ver }}/x86_64/stable/
    enabled: yes
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: Install docker engine (RHEL/CentOS)
  when: ansible_os_family == "RedHat"
  yum:
    name: "docker-ce-selinux-{{ docker_version }}.*"
    state: present