---  
# - name: Add Docker APT repository
#   when: ansible_os_family == "Debian"
#   apt_repository:
#     repo: deb https://download.docker.com/linux/ubuntu xenial stable
#     state: present
#     filename: "docker"

# - name: Install python3-apt package
#   when: ansible_os_family == "Debian"
#   apt:
#     name: python3-apt
#     state: present
#   become: yes

# - name: Install Docker Packages
#   when: ansible_os_family == "Debian"
#   apt:
#     update_cache: yes
#     cache_valid_time: 3600
#     name:
#       - docker
#       - docker-ce
#     state: present
#   become: yes
#   notify: start docker

# - name: Install docker engine on Ubuntu
#   when: ansible_os_family == "Debian"
#   apt:
#     name: docker
#     state: present
#   become: yes
#   notify: start docker
    
# - name: Add Docker yum repository on Centos{{ centos_os_ver }} 
#   # when: ansible_os_family == "RedHat"
#   yum_repository:
#     name: Docker
#     description: Docker Repository
#     file: docker
#     baseurl: https://download.docker.com/linux/centos/{{ centos_os_ver }}/x86_64/stable/
#     enabled: yes
#     gpgcheck: yes
#     gpgkey: https://download.docker.com/linux/centos/gpg

- name: Install docker engine on RHEL/CentOS
  # when: ansible_os_family == "RedHat"
  yum:
    name: docker
    state: latest
  # vars:
  #   ansible_python_interpreter: "{{ python2 }}"
  notify: start docker

- name: Start Docker Service
  become: true
  service:
    name: docker
    state: started
    enabled: yes


   