---
- name: Install packages
  include_tasks: packages.yml

- name: Setup cluster node
  include_tasks: node_setup.yml

- name: Install Docker Container Engine
  include_tasks: docker_setup.yml

- name: Install K8S Packages
  include_tasks: k8s_packages.yml

- name: Configure Kubernetes Master Node
  include_tasks: configure_master_node.yml
