---
- name: Install Packages on RedHat
  yum:
    name: ['wget', 'vim', 'unzip', 'telnet', 'nfs-utils', 'libselinux-python']
    state: installed
  # vars:
  #   ansible_python_interpreter: "{{ python }}"


