---
# handlers file for single-node-cluster
- name: start docker
  service:
    name: docker
    state: restarted
  become: yes

- name: reboot server
  shell: reboot


- name: yum update
  become: yes
  yum:
    name: '*'
    state: latest
    exclude: kernel*  