---
# handlers file for single-node-cluster
- name: start docker
  service:
    name: docker
    state: restarted
  become: yes

# Kubeadm Service


- name: restart kubeadm
  become: yes
  service:
    name: kubadm
    state: restarted

# Kubectl Service


- name: restart kubectl
  become: yes
  service:
    name: kubectl
    state: restarted

# Kubelet Service


- name: restart kubelet
  become: yes
  service:
    name: kubelet
    state: restarted